[workspace]
members = [
    "crates/any-context-core-rs",
    "crates/actx-installer",
    "crates/actx-lm",
    "crates/actx-agent",
    "crates/actx-cli",
]
resolver = "2"

[profile.dev]
opt-level = 0
debug = 1

[profile.release]
opt-level = 3
codegen-units = 16
lto = "off"
strip = true
debug = false
